name: zilliqa_ledger_flutter
description: A Zilliqa Ledger Plugin for Flutter. Supports sending transactions and getting accounts from Ledger hardware wallets.
version: 0.0.3
repository: https://github.com/zilpay/zilliqa_ledger_flutter
homepage: https://github.com/zilpay/zilliqa_ledger_flutter
issue_tracker: https://github.com/zilpay/zilliqa_ledger_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ledger_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zilpay.zilliqa_ledger_flutter
        pluginClass: ZilliqaLedgerFlutterPlugin
      ios:
        pluginClass: ZilliqaLedgerFlutterPlugin

topics:
  - ledger
  - blockchain
  - zilliqa
  - hardware-wallet
  - web3

funding:
  - https://github.com/sponsors/zilpay
